### ISSUE TITLE
Unable to deploy AVS with AV36P SKU

### ISSUE THREAD

**Issue by rybirk** [Azure/Enterprise-Scale-for-AVS#177]
Customer is deploying AVS via Terraform and unable to select the AV36P sku. https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/vmware/vmware_cluster_resource.go#L60-L69

**Comment by prasad3017** [comment]
@jchancellor-ms  This is the Terraform ask for AVS deployment. COuld you please check on this?

**Comment by prasad3017** [comment]
@jchancellor-ms  Looking for your help on this

**Comment by jchancellor-ms** [comment]
I've submitted issue https://github.com/hashicorp/terraform-provider-azurerm/issues/19538 to the AzureRM team.  I'll see if they'll allow me to submit a pull request since it is a simple list update. However, I won't be able to fully test it since I don't have access to a subscription with quota.  (But it should throw a no-quota exception instead of a validation exception.)

**Comment by jchancellor-ms** [comment]
@prasad3017 -  I've submitted pull request https://github.com/hashicorp/terraform-provider-azurerm/pull/19565 to the AzureRM team.  Will watch for it to be approved and merged into the next release.

**Comment by jchancellor-ms** [comment]
@prasad3017 and @rybirk - This functionality should now be available in version 3.35 of the AzureRM provider.   Please test and let me know if there are any continued issues.
