### ISSUE TITLE
BuildArm.ps1

### ISSUE THREAD

**Issue by sblair01** [Azure/Enterprise-Scale-for-AVS#214]
Hi, 

There is a Buildarm.ps1 file in the root level of the repo. It doesn't have an associated readme.md so it's not clear what the purpose of this file is. Should we move this to somewhere else?
cc @shaunjacob

**Comment by prasad3017** [comment]
Than you @sblair01 

Hello @husamhilal  is this something you can help to check out to resolve?

**Comment by husamhilal** [comment]
We build Azure deployment templates in Bicep. This script file is used to compile the .bicep files to .json (ARM templates) so templates can be executed as ARM templates instead of Bicep. 

I suggest moving it to Greenfield folder (if the purpose is to clean-up), but we need to test that it doesn't affect the logic that's written inside the script. 

Then we can add the readme file inside the Greenfield folder.

If all agree with what I stated, then we can proceed.
@sblair01  @prasad3017  @shaunjacob

**Comment by sblair01** [comment]
@husamhilal feel free to sync from main repo, create a branch, and a test. If it doesn't break anything there, I will ping @shaunjacob  and get this synced into main. Thanks!

**Comment by husamhilal** [comment]
@sblair01  @shaunjacob  I created this PR: https://github.com/Azure/Enterprise-Scale-for-AVS/pull/219

**Comment by prasad3017** [comment]
PR is approved so closing the issues. Please feel free to reopen
